Added logger timestamp.
google/weather-tools pull request #131
Opened 2022-03-29 21:26 UTC by pbattaglia

This makes it easier to monitor queue durations.

2022-03-31 00:50 UTC, alxmrs requested changes

2022-03-31 00:50 UTC, alxmrs commented on weather_dl/weather-dl
> +    logger.setLevel(logging.INFO)
This should probably be moved to the `configure_logger` function. 

https://github.com/google/weather-tools/blob/ecb194c7bc62d9d0ad3982cce24eb745a470be84/weather_dl/download_pipeline/pipeline.py#L48

2022-03-31 00:50 UTC, alxmrs commented on weather_dl/download_pipeline/parsers.py
> +        date_vals = date.split('-')
Please merge with main / clean up the commit history.

2022-04-05 18:02 UTC, alxmrs approved these changes
LGTM. Would you mind pasting a preview of what the logs look like after this change (e.g. a screenshot or a codeblock)? Before I merge, I want to understand what the effect will be.

2022-04-05 22:08 UTC, pbattaglia commented
Here's an example of what the logging looks like:

```INFO 22-04-05 12:30:33 apache_beam.runners.dataflow.dataflow_runner: 2022-04-05T11:30:32.196Z: JOB_MESSAGE_DEBUG: Workflow config is missing a default resource spec.
INFO 22-04-05 12:30:33 apache_beam.runners.dataflow.dataflow_runner: 2022-04-05T11:30:32.218Z: JOB_MESSAGE_DEBUG: Adding StepResource setup and teardown to workflow graph.
INFO 22-04-05 12:30:33 apache_beam.runners.dataflow.dataflow_runner: 2022-04-05T11:30:32.241Z: JOB_MESSAGE_DEBUG: Adding workflow start and stop steps.
INFO 22-04-05 12:30:33 apache_beam.runners.dataflow.dataflow_runner: 2022-04-05T11:30:32.264Z: JOB_MESSAGE_DEBUG: Assigning stage ids.
INFO 22-04-05 12:30:33 apache_beam.runners.dataflow.dataflow_runner: 2022-04-05T11:30:32.374Z: JOB_MESSAGE_DEBUG: Executing wait step start13
INFO 22-04-05 12:30:33 apache_beam.runners.dataflow.dataflow_runner: 2022-04-05T11:30:32.429Z: JOB_MESSAGE_BASIC: Executing operation GroupBy request limits/GroupByKey/Create
INFO 22-04-05 12:30:33 apache_beam.runners.dataflow.dataflow_runner: 2022-04-05T11:30:32.469Z: JOB_MESSAGE_DEBUG: Starting worker pool setup.```

2022-04-05 22:44 UTC, merged